### ISSUE TITLE
'env' file/folder package not in the open sourced repository

### ISSUE THREAD

**Issue by sushanth-d** [GilgameshD/GRADER#1]
Hi
Thank you for open sourcing the code. It was truly intriguing to read through the paper. 

I am trying to reproduce the results for the chemistry environment.
I can see that the train_agent.py tries to import ColorChangingRL from env in the following line:

`from env import ColorChangingRL`

However, in the repository I do not see any folders or files with the name 'env'.

In the README file you have mentioned that 

> "The released code only contains the Chemistry environment modified from this [repo](https://github.com/dido1998/CausalMBRL)." 

So I tried to use the ColorChangingRL class from the CausalMBRL repository (link: https://github.com/dido1998/CausalMBRL/blob/master/envs/chemistry_env_rl.py). But I was not able to successfully execute the training script. 

Could you provide some insights regarding this please?

Thank you!

**Comment by GilgameshD** [comment]
Thanks for reporting the bug. The /env folder was filtered out by .gitignore. I added it back.
